name: Unit tests with vitest

on:
  push:
    branches: [master, beta]
  pull_request:
    branches: [master, beta]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        id: pages
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit
